<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report [
    <!ELEMENT report (summary)>
    <!ELEMENT summary (dishes_sold, earnings, discounts_given)>
    
    <!ELEMENT dishes_sold (total)>
    <!ELEMENT earnings (total)>
    <!ELEMENT discounts_given (total)>
    
    <!ELEMENT total (#PCDATA)>
]>

<report>
    <summary>
        <dishes_sold>
            <total>12</total>
        </dishes_sold>
        <earnings>
            <total>â‚±770</total>
        </earnings>
        <discounts_given>
            <total>3</total>
        </discounts_given>
    </summary>
</report>
