<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sides [
    <!ELEMENT sides (side*)>
    <!ELEMENT side (sides_id, name, price, nutr_facts_id, stocks_id)>
    
    <!ELEMENT sides_id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT nutr_facts_id (#PCDATA)>
    <!ELEMENT stocks_id (#PCDATA)>
]>

<sides>
    <side>
        <sides_id>i201</sides_id>
        <name>Rice</name>
        <price>20</price>
        <nutr_facts_id>n201</nutr_facts_id>
        <stocks_id>s01</stocks_id>
    </side>
    <side>
        <sides_id>i202</sides_id>
        <name>Mixed Vegetables</name>
        <price>30</price>
        <nutr_facts_id>n202</nutr_facts_id>
        <stocks_id>s02</stocks_id>
    </side>
    <side>
        <sides_id>i203</sides_id>
        <name>Mashed Potatoes</name>
        <price>30</price>
        <nutr_facts_id>n203</nutr_facts_id>
        <stocks_id>s03</stocks_id>
    </side>
    <side>
        <sides_id>i204</sides_id>
        <name>Sliced Apple</name>
        <price>20</price>
        <nutr_facts_id>n204</nutr_facts_id>
        <stocks_id>s04</stocks_id>
    </side>
    <side>
        <sides_id>i205</sides_id>
        <name>test</name>
        <price>11</price>
        <nutr_facts_id>n205</nutr_facts_id>
        <stocks_id>s05</stocks_id>
    </side>
    <side>
        <sides_id>i206</sides_id>
        <name>test</name>
        <price>11</price>
        <nutr_facts_id>n206</nutr_facts_id>
        <stocks_id>s06</stocks_id>
    </side>
</sides>
